/t265:
  camera:
    ros__parameters:
      serial_no: 845412111144 # t265
      base_frame_id: t265_link
      fisheye1:
        enabled: true
        resolution: [848,800]
        fps: 30
      fisheye2:
        enabled: true
        resolution: [848,800]
        fps: 30
      accel0:
        enabled: true
      gyro0:
        enabled: true
      pose0:
        enabled: true